# Generated by Django 4.1.13 on 2023-12-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='allergies',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='blood_type',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='family_history',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='medications',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='past_diseases',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='surgeries',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='observations',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='patient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories.history')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories.history')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('observations', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('allergies', models.CharField(max_length=255, null=True)),
                ('medications', models.CharField(max_length=255, null=True)),
                ('past_diseases', models.CharField(max_length=255, null=True)),
                ('surgeries', models.CharField(max_length=255, null=True)),
                ('family_history', models.CharField(max_length=255, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histories.history')),
            ],
        ),
    ]
